// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9pZIxK8BK4-HqPqMUTGjbMx2hMBtc78M',
    appId: '1:360679595267:web:a5a0dd68cbd07efcba9d36',
    messagingSenderId: '360679595267',
    projectId: 'foodpanda-7ecb8',
    authDomain: 'foodpanda-7ecb8.firebaseapp.com',
    storageBucket: 'foodpanda-7ecb8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVvoUDdeQlX2N9W_R7IOAZWPZvha1CTv4',
    appId: '1:360679595267:android:612c02c7266f8510ba9d36',
    messagingSenderId: '360679595267',
    projectId: 'foodpanda-7ecb8',
    storageBucket: 'foodpanda-7ecb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYngytanAwYsEbv9Rcb43yavJyI4vFrck',
    appId: '1:360679595267:ios:56c88bbf6f576400ba9d36',
    messagingSenderId: '360679595267',
    projectId: 'foodpanda-7ecb8',
    storageBucket: 'foodpanda-7ecb8.appspot.com',
    androidClientId: '360679595267-d8vug52fld5q2tq60f1dpdcfp97d8skv.apps.googleusercontent.com',
    iosClientId: '360679595267-ieh78oq0p3db9l0kg59njtkhkmus8od4.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpandaSeller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYngytanAwYsEbv9Rcb43yavJyI4vFrck',
    appId: '1:360679595267:ios:bffa390e2101ff59ba9d36',
    messagingSenderId: '360679595267',
    projectId: 'foodpanda-7ecb8',
    storageBucket: 'foodpanda-7ecb8.appspot.com',
    androidClientId: '360679595267-d8vug52fld5q2tq60f1dpdcfp97d8skv.apps.googleusercontent.com',
    iosClientId: '360679595267-7fenlr4kr581qlbhc8kndq6b97rht6e4.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpandaSeller.RunnerTests',
  );
}
